#!/usr/bin/env ruby
require "pry"

class Questions

	def set_inital_values
		@questionList = []
		@args = ARGV
		@questionFile = "/Users/bnourse/questions.txt"
	end

	def read_into_array
		@questionList = File.readlines(@questionFile)
	end

	def disp
		for i in 0..@questionList.length-1
			questionNumber = i + 1
			puts "#{questionNumber}. #{@questionList[i]}"
		end
	end

	def add(newQuestion)
		@questionList.push(newQuestion)
		write_to_file
	end

	def remove(questionNumber)
		questionIndex = questionNumber - 1
		@questionList.delete_at(questionIndex)
	end

	def write_to_file
		open(@questionFile, 'w') do |f|
	      for question in @questionList
	      	question = question.chomp
	      	f.puts question
	      end
	    end
	end

	def run
		set_inital_values
		read_into_array
		doCommand(args[0], args[1])
	end

	def doCommand(command, commandValue)
		if command == nil
			disp
		else if command == "add"
			add(commandValue)
	end
end

q = Questions.new
q.run